export default {
    NEW_SESSION: 'NEW_SESSION',
    SAVE_SESSION: 'SAVE_SESSION',
    LOAD_SESSION: 'LOAD_SESSION',
    TAP_TERRITORY: 'TAP_TERRITORY',
    RESOLVE_ORDERS: 'RESOLVE_ORDERS',
    REVERT_TO_CURRENT_TURN: 'REVERT_TO_CURRENT_TURN',
    SET_TURN: 'SET_TURN',
    SET_ORDER_MODE: 'SET_ORDER_MODE'
}
