import {dip1900} from './board-spec';

let session = {
    title: "A Game",
    boardSpec: dip1900,
    turns: [
        [
            {power: "Great Britain", unit: "London", action: "Move", target: "English Channel", viaConvoy: false},
            {power: "Great Britain", unit: "Edinburgh", action: "Move", target: "North Sea", viaConvoy: false},
            {power: "Great Britain", unit: "Gibraltar", action: "Move", target: "Morocco", viaConvoy: false},
            {power: "Great Britain", unit: "Egypt", action: "Move", target: "Mid Atlantic Ocean", viaConvoy: false},
            {power: "Germany", unit: "Kiel", action: "Move", target: "Berlin", viaConvoy: false},
            {power: "Germany", unit: "Berlin", action: "Move", target: "Munich", viaConvoy: false},
            {power: "Germany", unit: "Munich", action: "Move", target: "Cologne", viaConvoy: false},
            {power: "Germany", unit: "Cologne", action: "Move", target: "Kiel", viaConvoy: false},
            {power: "France", unit: "Brest", action: "Move", target: "Picardy", viaConvoy: false},
            {power: "France", unit: "Paris", action: "Move", target: "Gascony", viaConvoy: false},
            {power: "France", unit: "Marseilles", action: "Move", target: "Spain", viaConvoy: false},
            {power: "France", unit: "Algeria", action: "Move", target: "Morocco", viaConvoy: false},
            {power: "Italy", unit: "Milan", action: "Move", target: "Switzerland", viaConvoy: false},
            {power: "Italy", unit: "Rome", action: "Move", target: "Piedmont", viaConvoy: false},
            {power: "Italy", unit: "Naples", action: "Move", target: "Ionian Sea", viaConvoy: false},
            {power: "Austria Hungary", unit: "Trieste", action: "Move", target: "Adriatic Sea", viaConvoy: false},
            {power: "Austria Hungary", unit: "Vienna", action: "Move", target: "Budapest", viaConvoy: false},
            {power: "Austria Hungary", unit: "Budapest", action: "Move", target: "Rumania", viaConvoy: false},
            {power: "Turkey", unit: "Constantinople", action: "Move", target: "Macedonia", viaConvoy: false},
            {power: "Turkey", unit: "Ankara", action: "Move", target: "Black Sea", viaConvoy: false},
            {power: "Turkey", unit: "Damascus", action: "Move", target: "Palestine", viaConvoy: false},
            {power: "Russia", unit: "St. Petersburg :: SC", action: "Move", target: "Gulf of Bothnia", viaConvoy: false},
            {power: "Russia", unit: "Moscow", action: "Move", target: "Ukraine", viaConvoy: false},
            {power: "Russia", unit: "Warsaw", action: "Move", target: "Galacia", viaConvoy: false},
            {power: "Russia", unit: "Sevastapol", action: "Move", target: "Rumania", viaConvoy: false},
        ],
        [
            {power: "Great Britain", unit: "North Sea", action: "Move", target: "Norway", viaConvoy: false},
            {power: "Great Britain", unit: "English Channel", action: "Move", target: "Picardy", viaConvoy: false},
            {power: "Great Britain", unit: "Gibraltar", action: "Support", targetUnit: "Mid Atlantic Ocean", target: "Morocco"},
            {power: "Great Britain", unit: "Mid Atlantic Ocean", action: "Move", target: "Morocco", viaConvoy: false},
            {power: "Germany", unit: "Denmark", action: "Support", targetUnit: "Kiel"},
            {power: "Germany", unit: "Kiel", action: "Hold", viaConvoy: false},
            {power: "Germany", unit: "Netherlands", action: "Hold", viaConvoy: false},
            {power: "Germany", unit: "Munich", action: "Hold"},
            {power: "France", unit: "Picardy", action: "Move", target: "English Channel", viaConvoy: false},
            {power: "France", unit: "Gascony", action: "Move", target: "Spain", viaConvoy: false},
            {power: "France", unit: "Spain", action: "Move", target: "Portugal", viaConvoy: false},
            {power: "France", unit: "Algeria", action: "Move", target: "Morocco", viaConvoy: false},
            {power: "Italy", unit: "Switzerland", action: "Hold"},
            {power: "Italy", unit: "Piedmont", action: "Move", target: "Marseilles", viaConvoy: false},
            {power: "Italy", unit: "Ionian Sea", action: "Move", target: "Tripoltania", viaConvoy: false},
            {power: "Austria Hungary", unit: "Adriatic Sea", action: "Move", target: "Ionian Sea", viaConvoy: false},
            {power: "Austria Hungary", unit: "Vienna", action: "Move", target: "Budapest", viaConvoy: false},
            {power: "Austria Hungary", unit: "Budapest", action: "Move", target: "Rumania", viaConvoy: false},
            {power: "Turkey", unit: "Macedonia", action: "Move", target: "Greece", viaConvoy: false},
            {power: "Turkey", unit: "Black Sea", action: "Support", targetUnit: "Sevastapol", target: "Rumania"},
            {power: "Turkey", unit: "Palestine", action: "Move", target: "Egypt", viaConvoy: false},
            {power: "Russia", unit: "Gulf of Bothnia", action: "Move", target: "Sweden", viaConvoy: false},
            {power: "Russia", unit: "Ukraine", action: "Move", target: "Warsaw", viaConvoy: false},
            {power: "Russia", unit: "Galacia", action: "Support", targetUnit: "Sevastapol", target: "Rumania"},
            {power: "Russia", unit: "Sevastapol", action: "Move", target: "Rumania", viaConvoy: false},
        ],
        [
            {power: "Great Britain", unit: "London", action: "Build", unitType: "army"},
            {power: "France", unit: "Paris", action: "Build", unitType: "army"},
            {power: "Italy", unit: "Rome", action: "Build", unitType: "fleet"},
            {power: "Italy", unit: "Naples", action: "Build", unitType: "fleet"},
            {power: "Italy", unit: "Milan", action: "Build", unitType: "army"},
            {power: "Austria Hungary", unit: "Vienna", action: "Build", unitType: "army"},
            {power: "Turkey", unit: "Constantinople", action: "Build", unitType: "army"},
            {power: "Turkey", unit: "Damascus", action: "Build", unitType: "fleet"},
            {power: "Germany", unit: "Cologne", action: "Build", unitType: "army"},
            {power: "Germany", unit: "Berlin", action: "Build", unitType: "army"},
            {power: "Russia", unit: "St. Petersburg :: NC", action: "Build", unitType: "fleet"},
        ],
        [
        ]
    ]
}


module.exports = {
    session: session,
}