import {dip1900} from './board-spec';

let session = {
    title: "War in Q4",
    boardSpec: dip1900,
    turns: [
        [{"power":"Russia","unit":"St. Petersburg :: SC","action":"Move","target":"Gulf of Bothnia","viaConvoy":false},{"power":"Russia","unit":"Moscow","action":"Hold","target":"Moscow"},{"power":"Russia","unit":"Warsaw","action":"Move","target":"Livonia","viaConvoy":false},{"power":"Russia","unit":"Sevastapol","action":"Move","target":"Rumania","viaConvoy":false},{"power":"Turkey","unit":"Constantinople","action":"Move","target":"Bulgaria","viaConvoy":false},{"power":"Turkey","unit":"Ankara","action":"Move","target":"Constantinople","viaConvoy":false},{"power":"Turkey","unit":"Damascus","action":"Move","target":"Palestine","viaConvoy":false},{"power":"Great Britain","unit":"Egypt","action":"Hold","target":"Egypt"},{"power":"France","unit":"Algeria","action":"Move","target":"Tunisia","viaConvoy":false},{"power":"Great Britain","unit":"Gibraltar","action":"Move","target":"Morocco","viaConvoy":false},{"power":"France","unit":"Marseilles","action":"Move","target":"Spain","viaConvoy":false},{"power":"France","unit":"Paris","action":"Move","target":"Gascony","viaConvoy":false},{"power":"France","unit":"Brest","action":"Move","target":"Picardy","viaConvoy":false},{"power":"Germany","unit":"Cologne","action":"Move","target":"Belgium","viaConvoy":false},{"power":"Germany","unit":"Munich","action":"Move","target":"Alsace","viaConvoy":false},{"power":"Germany","unit":"Berlin","action":"Move","target":"Kiel","viaConvoy":false},{"power":"Germany","unit":"Kiel","action":"Move","target":"Denmark","viaConvoy":false},{"power":"Great Britain","unit":"Edinburgh","action":"Move","target":"Norwegian Sea","viaConvoy":false},{"power":"Great Britain","unit":"London","action":"Move","target":"North Sea","viaConvoy":false},{"power":"Italy","unit":"Milan","action":"Move","target":"Switzerland","viaConvoy":false},{"power":"Italy","unit":"Rome","action":"Move","target":"Piedmont","viaConvoy":false},{"power":"Italy","unit":"Naples","action":"Move","target":"Ionian Sea","viaConvoy":false},{"power":"Austria Hungary","unit":"Trieste","action":"Move","target":"Bosnia","viaConvoy":false},{"power":"Austria Hungary","unit":"Vienna","action":"Move","target":"Budapest","viaConvoy":false},{"power":"Austria Hungary","unit":"Budapest","action":"Move","target":"Serbia","viaConvoy":false}],
        [{"power":"Great Britain","unit":"Norwegian Sea","action":"Move","target":"Norway","viaConvoy":false},{"power":"Russia","unit":"Livonia","action":"Move","target":"Sweden","viaConvoy":true},{"power":"Russia","unit":"Gulf of Bothnia","action":"Convoy","target":"Sweden","targetUnit":"Livonia"},{"power":"Great Britain","unit":"North Sea","action":"Move","target":"Denmark","viaConvoy":false},{"power":"Germany","unit":"Denmark","action":"Move","target":"Baltic Sea","viaConvoy":false},{"power":"Germany","unit":"Kiel","action":"Move","target":"Netherlands","viaConvoy":false},{"power":"Germany","unit":"Alsace","action":"Move","target":"Burgundy","viaConvoy":false},{"power":"Germany","unit":"Belgium","action":"Support","target":"Burgundy","targetUnit":"Alsace"},{"power":"Italy","unit":"Piedmont","action":"Move","target":"Marseilles","viaConvoy":false},{"power":"Italy","unit":"Switzerland","action":"Support","target":"Marseilles","targetUnit":"Piedmont"},{"power":"France","unit":"Spain","action":"Move","target":"Portugal","viaConvoy":false},{"power":"France","unit":"Gascony","action":"Move","target":"Spain","viaConvoy":false},{"power":"Great Britain","unit":"Morocco","action":"Hold","target":"Morocco"},{"power":"France","unit":"Tunisia","action":"Move","target":"Tripolitania","viaConvoy":false},{"power":"Great Britain","unit":"Egypt","action":"Hold","target":"Egypt"},{"power":"Turkey","unit":"Palestine","action":"Hold","target":"Palestine"},{"power":"Italy","unit":"Ionian Sea","action":"Move","target":"Greece","viaConvoy":false},{"power":"Turkey","unit":"Constantinople","action":"Move","target":"Macedonia :: EC","viaConvoy":false},{"power":"Turkey","unit":"Bulgaria","action":"Support","target":"Macedonia :: EC","targetUnit":"Constantinople"},{"power":"Austria Hungary","unit":"Bosnia","action":"Move","target":"Macedonia","viaConvoy":false},{"power":"Austria Hungary","unit":"Budapest","action":"Hold","target":"Budapest"},{"power":"Austria Hungary","unit":"Serbia","action":"Hold","target":"Serbia"},{"power":"Russia","unit":"Moscow","action":"Move","target":"Ukraine","viaConvoy":false},{"power":"France","unit":"Picardy","action":"Hold","target":"Picardy"}],
        [{"power":"Russia","unitType":"fleet","action":"Build","unit":"Sevastapol"},{"power":"Russia","unitType":"army","action":"Build","unit":"Warsaw"},{"power":"Turkey","unitType":"fleet","action":"Build","unit":"Damascus"},{"power":"Italy","unitType":"fleet","action":"Build","unit":"Naples"},{"power":"Italy","unitType":"fleet","action":"Build","unit":"Rome"},{"power":"Italy","unitType":"army","action":"Build","unit":"Milan"},{"power":"Austria Hungary","unitType":"army","action":"Build","unit":"Trieste"},{"power":"Germany","unitType":"fleet","action":"Build","unit":"Kiel"},{"power":"Germany","unitType":"army","action":"Build","unit":"Berlin"},{"power":"Great Britain","unitType":"fleet","action":"Build","unit":"London"},{"power":"Great Britain","unitType":"fleet","action":"Build","unit":"Liverpool"},{"power":"Great Britain","unitType":"fleet","action":"Build","unit":"Edinburgh"},{"power":"France","unitType":"fleet","action":"Build","unit":"Brest"},{"power":"France","unitType":"army","action":"Build","unit":"Paris"}],
    ]
}


module.exports = {
    session: session,
}